#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickInputMappingPropertySettings

#include <SDK/Basic.hpp>
#include <SDK/BrickRigs_structs.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_BrickInputMappingPropertySettings.BP_BrickInputMappingPropertySettings
// 0x00E8 (0x00E8 - 0x0000)
struct FBP_BrickInputMappingPropertySettings final
{
public:
	struct FInputTableRow                         InputTableRow_13_F26DAD1F43B0F350BB29ACB63F12A7B7; // 0x0000(0x00E0)(Edit, BlueprintVisible)
	bool                                          bIsNegativeAxisMapping_10_44BD6B7140D137E6097861BF6498BD96; // 0x00E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_NAMESPACE_END
