#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickPropertyType

#include <SDK/Basic.hpp>


SDK_NAMESPACE_START

// UserDefinedEnum BP_BrickPropertyType.BP_BrickPropertyType
// NumValues: 0x0006
enum class EBP_BrickPropertyType : uint8
{
	Bool								 = 0,
	Numeric								 = 1,
	Color								 = 2,
	Text								 = 3,
	InputMapping                         = 4,
	BP_MAX                               = 5,
};

SDK_NAMESPACE_END
