#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ColorBrickPropertySettings

#include <SDK/Basic.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_ColorBrickPropertySettings.BP_ColorBrickPropertySettings
// 0x0001 (0x0001 - 0x0000)
struct FBP_ColorBrickPropertySettings final
{
public:
	bool                                          bHasAlphaChannel_1_CCBACD864F941E45CB5EE9BA75E96F8E; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_NAMESPACE_END
