#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EBrickValidityState

#include <SDK/Basic.hpp>


SDK_NAMESPACE_START

// UserDefinedEnum BP_EBrickValidityState.BP_EBrickValidityState
// NumValues: 0x0005
enum class EBP_EBrickValidityState : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	BP_MAX                                   = 4,
};

SDK_NAMESPACE_END
