#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FBrickPropertyFocusEvent

#include <SDK/Basic.hpp>

#include "BP_EBrickValidityState_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct BP_FBrickPropertyFocusEvent.BP_FBrickPropertyFocusEvent
// 0x0060 (0x0060 - 0x0000)
struct FBP_FBrickPropertyFocusEvent final
{
public:
	class FName                                   SubPropertyName_12_631AECC5466EBB148337A6A974351BEE; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsFocused_13_E43B5D61485A4A303B52E5B8C29DE138;    // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class UBrick*, EBP_EBrickValidityState>  ObjectsToHighlight_10_BACBA6B541AC1EF45CCDFE9860ABE524; // 0x0010(0x0050)(Edit, BlueprintVisible)
};

SDK_NAMESPACE_END
