#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FBrickPropertyChangedEvent

#include <SDK/Basic.hpp>
#include <SDK/BrickRigs_Structs.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_FBrickPropertyChangedEvent.BP_FBrickPropertyChangedEvent
// 0x0058 (0x0058 - 0x0000)
struct FBP_FBrickPropertyChangedEvent final
{
public:
	class ABasePlayerController*                  Player_2_F9380255487A53F6C096328819F57FDF;         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 FullPropertyName_5_0E9BA9054DCDCCF1BD1FFE845DDD6798; // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FName                                   PropertyName_12_0BBEF14E41D1C0E9BCA3CABB835F8919;  // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           PropertyChain_13_7B2F23E941B2FB23EC7DCB815FE7ABCF; // 0x0020(0x0010)(Edit, BlueprintVisible)
	int32                                         PropertyChainDepth_22_70B10BCC4A8159E6974175B21CCB5BAC; // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UBrick*>                         ModifiedObjects_27_45C139284E153BB966F2ABB40D6CB9B8; // 0x0038(0x0010)(Edit, BlueprintVisible)
	class UBrick*                                 ActiveObject_39_5152782A44A0F9E877CE59AE6ED6415E;  // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EValueChangedEventType                        EventType_40_2EFEF5D549F5FB61337FA5BBE6427D46;     // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bExternalChange_36_25F6B20D4287BCDF12F998B132760E2B; // 0x0051(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bUpdateAllProperties_37_4E84B6FE48E2CB330DFB3BB68419D0CA; // 0x0052(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_NAMESPACE_END
