#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IBrickPropertyInterface

#include <SDK/Basic.hpp>

#include "BP_ShouldCallSuperSettings_structs.hpp"
#include "BP_FBrickPropertyDeclaration_structs.hpp"
#include "BP_FBrickPropertyFocusEvent_structs.hpp"
#include "BP_FBrickPropertyChangedEvent_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.CanModifyBrickProperties
// 0x0001 (0x0001 - 0x0000)
struct BP_IBrickPropertyInterface_C_CanModifyBrickProperties final
{
public:
	bool                                          Return_Value;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.PostModifyBrickProperty
// 0x0058 (0x0058 - 0x0000)
struct BP_IBrickPropertyInterface_C_PostModifyBrickProperty final
{
public:
	struct FBP_FBrickPropertyChangedEvent         Event;                                             // 0x0000(0x0058)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperPostModifyBrickProperty
// 0x0002 (0x0002 - 0x0000)
struct BP_IBrickPropertyInterface_C_ShouldCallSuperPostModifyBrickProperty final
{
public:
	struct FBP_ShouldCallSuperSettings            Return;                                            // 0x0000(0x0002)(Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperUpdateFocusedBrickProperty
// 0x0002 (0x0002 - 0x0000)
struct BP_IBrickPropertyInterface_C_ShouldCallSuperUpdateFocusedBrickProperty final
{
public:
	struct FBP_ShouldCallSuperSettings            Return;                                            // 0x0000(0x0002)(Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.UpdateFocusedBrickProperty
// 0x0060 (0x0060 - 0x0000)
struct BP_IBrickPropertyInterface_C_UpdateFocusedBrickProperty final
{
public:
	struct FBP_FBrickPropertyFocusEvent           Event;                                             // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ReflectBrickProperties
// 0x0010 (0x0010 - 0x0000)
struct BP_IBrickPropertyInterface_C_ReflectBrickProperties final
{
public:
	TArray<struct FBP_FBrickPropertyDeclaration>  Return;                                            // 0x0000(0x0010)(Parm, OutParm)
};

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperReflectBrickProperties
// 0x0002 (0x0002 - 0x0000)
struct BP_IBrickPropertyInterface_C_ShouldCallSuperReflectBrickProperties final
{
public:
	struct FBP_ShouldCallSuperSettings            Return;                                            // 0x0000(0x0002)(Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
