#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IBrickPropertyInterface

#include <SDK/Basic.hpp>

#include "BP_IBrickPropertyInterface_classes.hpp"
#include "BP_IBrickPropertyInterface_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.CanModifyBrickProperties
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return_Value                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBP_IBrickPropertyInterface_C::CanModifyBrickProperties(bool* Return_Value)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "CanModifyBrickProperties");

	Params::BP_IBrickPropertyInterface_C_CanModifyBrickProperties Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Return_Value != nullptr)
		*Return_Value = Parms.Return_Value;
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.PostModifyBrickProperty
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBP_FBrickPropertyChangedEvent&Event                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void IBP_IBrickPropertyInterface_C::PostModifyBrickProperty(const struct FBP_FBrickPropertyChangedEvent& Event)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "PostModifyBrickProperty");

	Params::BP_IBrickPropertyInterface_C_PostModifyBrickProperty Parms{};

	Parms.Event = std::move(Event);

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperPostModifyBrickProperty
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBP_ShouldCallSuperSettings*     Return                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBP_IBrickPropertyInterface_C::ShouldCallSuperPostModifyBrickProperty(struct FBP_ShouldCallSuperSettings* Return)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "ShouldCallSuperPostModifyBrickProperty");

	Params::BP_IBrickPropertyInterface_C_ShouldCallSuperPostModifyBrickProperty Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = std::move(Parms.Return);
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperUpdateFocusedBrickProperty
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBP_ShouldCallSuperSettings*     Return                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBP_IBrickPropertyInterface_C::ShouldCallSuperUpdateFocusedBrickProperty(struct FBP_ShouldCallSuperSettings* Return)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "ShouldCallSuperUpdateFocusedBrickProperty");

	Params::BP_IBrickPropertyInterface_C_ShouldCallSuperUpdateFocusedBrickProperty Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = std::move(Parms.Return);
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.UpdateFocusedBrickProperty
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBP_FBrickPropertyFocusEvent&Event                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void IBP_IBrickPropertyInterface_C::UpdateFocusedBrickProperty(const struct FBP_FBrickPropertyFocusEvent& Event)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "UpdateFocusedBrickProperty");

	Params::BP_IBrickPropertyInterface_C_UpdateFocusedBrickProperty Parms{};

	Parms.Event = std::move(Event);

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ReflectBrickProperties
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBP_FBrickPropertyDeclaration>*Return                                                 (Parm, OutParm)

void IBP_IBrickPropertyInterface_C::ReflectBrickProperties(TArray<struct FBP_FBrickPropertyDeclaration>* Return)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "ReflectBrickProperties");

	Params::BP_IBrickPropertyInterface_C_ReflectBrickProperties Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = std::move(Parms.Return);
}


// Function BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C.ShouldCallSuperReflectBrickProperties
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBP_ShouldCallSuperSettings*     Return                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBP_IBrickPropertyInterface_C::ShouldCallSuperReflectBrickProperties(struct FBP_ShouldCallSuperSettings* Return)
{
	static class UFunction* Func = nullptr;
	std::string ClassName = AsUObject()->Class->Name.ToString();

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction(ClassName.c_str(), "ShouldCallSuperReflectBrickProperties");

	Params::BP_IBrickPropertyInterface_C_ShouldCallSuperReflectBrickProperties Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = std::move(Parms.Return);
}


SDK_NAMESPACE_END
