#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IBrickPropertyInterface

#include <SDK/Basic.hpp>
#include <SDK/CoreUObject_classes.hpp>


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_IBrickPropertyInterface.BP_IBrickPropertyInterface_C
// 0x0000 (0x0000 - 0x0000)
class IBP_IBrickPropertyInterface_C final
{
public:
	void CanModifyBrickProperties(bool* Return_Value);
	void PostModifyBrickProperty(const struct FBP_FBrickPropertyChangedEvent& Event);
	void ShouldCallSuperPostModifyBrickProperty(struct FBP_ShouldCallSuperSettings* Return);
	void ShouldCallSuperUpdateFocusedBrickProperty(struct FBP_ShouldCallSuperSettings* Return);
	void UpdateFocusedBrickProperty(const struct FBP_FBrickPropertyFocusEvent& Event);
	void ReflectBrickProperties(TArray<struct FBP_FBrickPropertyDeclaration>* Return);
	void ShouldCallSuperReflectBrickProperties(struct FBP_ShouldCallSuperSettings* Return);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IBrickPropertyInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IBrickPropertyInterface_C")
	}
	static class IBP_IBrickPropertyInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBP_IBrickPropertyInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

SDK_NAMESPACE_END
