#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NumericBrickPropertySettings

#include <SDK/Basic.hpp>

#include <SDK/CoreUObject_structs.hpp>
#include <SDK/BrickRigs_structs.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_NumericBrickPropertySettings.BP_NumericBrickPropertySettings
// 0x0020 (0x0020 - 0x0000)
struct FBP_NumericBrickPropertySettings final
{
public:
	ENumericValueType                             ValueType_2_CD317FE24E85FE7D02AC699CA204CD82;      // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                ValueRangeMin_6_853D06F245BFA933845C069F54279A62;  // 0x0004(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ValueRangeMax_8_3A53C8914D3ABA38F103BD83DA3674EA;  // 0x0010(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFluAxisLock                                  AxisLock_11_76843DC84328B4FFF5C254BE82108C7A;      // 0x001C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

SDK_NAMESPACE_END
