#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShouldCallSuperSettings

#include <SDK/Basic.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_ShouldCallSuperSettings.BP_ShouldCallSuperSettings
// 0x0002 (0x0002 - 0x0000)
struct FBP_ShouldCallSuperSettings final
{
public:
	bool                                          ShouldCallSuper_1_3CC922DD4B3C9B04AF8CC79AF56C037B; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallAtStart_3_2B65F40F4734A4579FD5929B66219043;    // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_NAMESPACE_END
