#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TextBrickPropertySettings

#include <SDK/Basic.hpp>


SDK_NAMESPACE_START

// UserDefinedStruct BP_TextBrickPropertySettings.BP_TextBrickPropertySettings
// 0x0008 (0x0008 - 0x0000)
struct FBP_TextBrickPropertySettings final
{
public:
	int32                                         MaxTextLength_2_A571447D4E82909C54E42394E3B94752;  // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsPassword_5_FCD7939A44936B02C225E69331E9BC06;    // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bAllowMultiline_7_C87EB39A43E6C1C1DA59B38AE010990A; // 0x0005(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bIsUserText_9_7F88D4994617E060CD962DB6E8E135B7;    // 0x0006(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_NAMESPACE_END
